version: '3'

services:
  recdin-whatsapp-api:
    build:
      context: ./recdin-whatsapp-api
      dockerfile: Dockerfile
    image: recdin_app
    container_name: recdin_app
    hostname: recdin_app
    ports:
      - 3030:3000
    tty: true
    depends_on:
      - postgres
      - wppconnect-server
    volumes:
      - ./recdin-whatsapp-api:/recdin-whatsapp-api
    env_file:
      - ./recdin-whatsapp-api/.env
    command: bash -c "foreman s -f Procfile.dev"
    networks:
      - recdin-network

  postgres:
    image: postgres:12.14
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Recdin2023!
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - recdin-network

  wppconnect-server:
    build:
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    entrypoint: docker-entrypoint.sh yarn dev
    networks:
      - recdin-network
    ports:
      - 21465:21465
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  recdin-network:
    driver: bridge

volumes:
  postgres:
  recdin-whatsapp-api: