version: '3'

services:
  recdin-whatsapp-api:
    build:
      context: ./recdin-whatsapp-api
      dockerfile: Dockerfile
    image: recdin_app
    container_name: recdin_app
    hostname: recdin_app
    ports:
      - 3030:3000
    tty: true
    depends_on:
      - db
      - wppconnect-server
    volumes:
      - ./recdin-whatsapp-api:/recdin-whatsapp-api
    env_file:
      - ./recdin-whatsapp-api/.env
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
    networks:
      - recdin-network

  sidekiq:
    build:
      context: ./recdin-whatsapp-api
      dockerfile: Dockerfile
    image: sidekiq
    container_name: sidekiq
    hostname: sidekiq
    tty: true
    depends_on:
      - db
    volumes:
      - ./recdin-whatsapp-api:/recdin-whatsapp-api
    command: bash -c "redis-server --requirepass Recdin2023! --daemonize yes && bundle exec sidekiq -C config/sidekiq.yml"
    ports:
      - 6379:6379
    networks:
      - recdin-network

  db:
    image: postgres:12.14
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Recdin2023!
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - recdin-network

  wppconnect-server:
    build:
      context: ./wppconnect-server
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    entrypoint: docker-entrypoint.sh yarn dev
    networks:
      - recdin-network
    ports:
      - 21465:21465
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  recdin-network:
    driver: bridge

volumes:
  postgres:
  recdin-whatsapp-api: