default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch('DATABASE_HOST') { 'db' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'Recdin2023!' } %>

development:
  <<: *default
  database: recdin_dev

test:
  <<: *default
  database: recdin_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { 'recdin_db' } %>
